
server: # 端口号
  port: 8888
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_db?useSSL=false&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Altran2021@@@

#sharding:
#  jdbc:
#    dataSource:
#      names: db-test0
#      # 配置主库
#      db-test0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
#        username: root
#        password: Altran2021@@@
#        #最大连接数
#        maxPoolSize: 20
##      db-test1: # 配置第一个从库
##        type: com.alibaba.druid.pool.DruidDataSource
##        driverClassName: com.mysql.jdbc.Driver
##        url: jdbc:mysql://ip:3306/database1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
##        username: 账户
##        password: 密码
##        maxPoolSize: 20
##      db-test2: # 配置第二个从库
##        type: com.alibaba.druid.pool.DruidDataSource
##        driverClassName: com.mysql.jdbc.Driver
##        url: jdbc:mysql://ip:3306/database2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
##        username: 账户
##        password: 密码
##        maxPoolSize: 20
#    tables:
#      t_order:
#        actualDataNodes: db-test0.t_order_$‐>{1..2}
#        tableStrategy:
#          inline:
#            shardingColumn: order_id
#            algorithmExpression: t_order_$‐>{order_id % 2 + 1}
#        keyGenerator:
#          type: SNOWFLAKE
#          column: order_id
#    config:
#      masterslave: # 配置读写分离
#        load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
#        name: db1s2
#        master-data-source-name: db-test0
#        slave-data-source-names: db-test1,db-test2
#    props:
#      sql:
#        show: true # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
spring:
  main:
    allow-bean-definition-overriding: true # 允许重名的bean可以被覆盖
  jpa:
    hibernate:
      ddl-auto: none # 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      naming: # 驼峰命名法
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true # 打印sql
